name = "portfolio"
compatibility_date = "2024-01-01"
main = "functions/[[path]].js"

# KV Namespaces (optional - can be removed if not used)
# kv_namespaces = [
#   { id = "MY_KV", binding="MY_KV" }
# ]
